make `mpie-cmti` standalone
pyiron/docker-stacks pull request #426
Opened 2024-11-29 16:21 UTC by mbruns91

This PR makes the `mpie_cmti` image definition "standalone", i.e. the layering starts with `jupyter/base-notebook:ubuntu-22.0`.

Before, the image was drived from `pyiron`, which was itself derived from `md`, which was derived from `base`, which was the only standalone image definition in `docker-stacks`.
Especially for this image, this makes managing the env easier, which is important as the shared conda environment on our cluster is based on this.

Broken down, I made some changes to `Dockerfile`, concatenating neccessary parts from the `Dockerfiles` of the previous "inheritance-chain". Similarly, I concatenated the `environment.yml` from all those image definitions

2024-11-29 16:28 UTC, mbruns91 commented
@niklassiemer you think this is okay?

Ich started the container locally and ran
```
mamba list
```
and compared the output with the output of running the same command on cmti; they are the same.

@jan-janssen : Just added you to make you aware of this change.

2024-11-29 16:36 UTC, mbruns91 commented
Actually I think this image is smaller; I'm about to leave my desk, so I can check tomorrow or so.

The container started from the image defined here is basically empty.
Maybe (in another PR) we could add some notebooks for typical tests we do to check our environment. This way, one can do those checks easily from a local container instance. I'm thinking about the typical imports, plugins, ...; stuff like that.

2024-11-29 18:28 UTC, niklassiemer requested changes
We need to resync the dependencies. Some of them decreased, but probably I did not find all of them. E.g. it seems that bokeh and maxvolpy are not in the list any more? I will check again the next days :)

2024-11-29 18:28 UTC, niklassiemer commented on mpie_cmti/environment.yml
> +- calphy =1.3.10
```suggestion
- calphy =1.3.11
```

2024-11-29 18:28 UTC, niklassiemer commented on mpie_cmti/environment.yml
> +- pyiron_workflow =0.11.0
```suggestion
- pyiron_workflow =0.11.2
- pyironflow =0.0.4
```

2024-11-29 18:28 UTC, niklassiemer commented on mpie_cmti/environment.yml
> +- pyxtal =1.0.4
```suggestion
- pyxtal =1.0.5
```

2024-11-29 18:28 UTC, niklassiemer commented on mpie_cmti/environment.yml
> +- pyiron_base =0.10.2
```suggestion
- pyiron_base =0.10.8
```

2024-11-29 18:28 UTC, niklassiemer commented on mpie_cmti/environment.yml
> +- pyiron_atomistics =0.6.13
```suggestion
- pyiron_atomistics =0.6.17
```

2024-11-29 18:28 UTC, niklassiemer commented on mpie_cmti/environment.yml
> +- llama-index =0.11.16
```suggestion
- llama-index =0.12.1
```

2024-12-04 14:32 UTC, mbruns91 commented
Ok, so upon concatenating the `environment.yml` from the image definitions of `pyiron`, `base` and `md` there occurred some merge conflict. Upon resolving this I seem to have removed some packages accidentially... I hope the last commit fixed that.

2024-12-04 15:26 UTC, mbruns91 commented
Environment-wise everything seems to be okay now. But now the image(s) are too large.
The `mpie_cmti` image is not actrually too large. But it now, as it's "standalone", doesn't share any layers with the other images anymore, so the device volume (the runners diks space) is filled faster.
This already an issue in the past, right? I think we could circumvent this, if not all steps of the building/testing were performed on the same runner instance.

We could either

- try to only build & test the images derived from the files on  the affected directory of a PR (e.g. in this case `mpie_cmti` *only*). I think this could be a bit ticky but doable. However it would increase the complexity of the CI/CD pipeline.
- make seperate repos for each image and make "docker-stacks" an organization.

What do you think, @niklassiemer?

2024-12-04 15:46 UTC, niklassiemer commented
Now I tried to split the testing to two VMs like before in #347. Back then I failed (and the issue was not to pressing) since all the builds needed to be in one VM. Now, this is not intended this way any longer!

2024-12-06 12:07 UTC, mbruns91 commented
Let's merge this PR and do the splitting for the test and release in another PR. @niklassiemer , can you please approve the changes?

2024-12-06 12:22 UTC, niklassiemer commented
Hmm... the code in test and push is quite similar and I would expect the push to break due to the changes in the cmti/Dockerfile. Thus, let me take over the responsibility and I try to get the release action aligned with the test action before merging it in.

2024-12-06 12:40 UTC, mbruns91 commented
Yeah, you're right. You really want to do it? I can take care of it as well.

2024-12-06 14:19 UTC, mbruns91 commented
I really don't like to do all of this in this PR, it appears messy to me.

I opened another (draft) PR where I'm working on the CI improvements and applied the same changes done here to `testing.yml`.

2024-12-06 16:35 UTC, niklassiemer commented
The problem is a bit that these things are indeed coupled... i.e. you need the Dockerfile change to build standalone and you need the ci change that this fits into one VM... probably we need stacked PRs to have it clean :)

2025-02-21 11:38 UTC, niklassiemer commented
ToDo:
- [ ] `Cache saved with key: cmti_env_$(date +%F)` is not as intended!
- [ ] `pip_check` should also be a dependency of `build_cmti`

2025-02-21 15:13 UTC, niklassiemer approved these changes
I am happy with this now. @mbruns91 could you have a look?

2025-02-24 16:27 UTC, merged